#!perl

##################
#
# This file was automatically generated by ZooZ.pl v1.2
# on Fri Jul  2 14:59:28 2010.
# Project: Project 1
# File:    F:/perl scripts/GCODE 2/gcode.zooz
#
##################

#
# Headers
#
use strict;
use warnings;


use Tk 804;

#
# Global variables
#
my (
     # MainWindow
     $MW,

     # Hash of all widgets
     %ZWIDGETS,
    );

#
# User-defined variables (if any)
#
my $opt_3 = 'O3';

my $param_3 = 'P3';

my $param_1 = 'P1';

my $opt_4 = 'O4';

my $param_4 = 'P4';

my %command_list = (
          'Travel/Feedrate' => 'G1',
          'E min Windup guard' => 'M124',
          'Set Home' => 'G92',
          'Cancel Print, CLR Buffer' => 'M112',
          'Move Rapidly' => 'G0',
          'Go Home' => 'G28',
          'E Max windup guard' => 'M123',
          'Set PWM for Extruder' => 'M113',
          'Set E D Gain' => 'M122',
          'Go Home/Intermediate Point' => 'G30',
          'Set E I Gain' => 'M121',
          'Arc-Clockwise' => 'G2',
          'Reset Line Count' => 'M110',
          'Set E Temp/Wait' => 'M109',
          'Dwell' => 'G4',
          'Incremental Positioning' => 'G91',
          'Set E P Gain' => 'M120',
          'Cooling Fan Off' => 'M107',
          'Arc-CCW' => 'G3',
          'Inches as Units' => 'G20',
          'Close Valve' => 'M127',
          'Set Extruder Temp' => 'M104',
          'Debug Mode' => 'M111',
          'Open Valve' => 'M126',
          'mm as Units' => 'G21',
          'Absolute Positioning' => 'G90',
          'Get Extruder Temp' => 'M105',
          'Cooling Fan On' => 'M106',
          'Return Coords' => 'M114'
        );

my $line = '0000';

my $file = 'gcode';

my $opt_2 = 'O2';

my $command = '0';

my $optional_delete = '0';

my $block = ' ';

my $opt_1 = 'O1';

my $ext = '.tap';

my $NLine = 'N'.$line;

my $param_2 = 'P2';

my @queue = ();


######################
#
# Create the MainWindow
#
######################

$MW = MainWindow->new;

######################
#
# Load any images and fonts
#
######################
ZloadImages();
ZloadFonts ();



# Widget Label1 isa Label
$ZWIDGETS{'Label1'} = $MW->Label(
   -text => 'G-Code Writer.',
  )->grid(
   -row    => 0,
   -column => 0,
  );

# Widget Checkbutton1 isa Checkbutton
$ZWIDGETS{'Checkbutton1'} = $MW->Checkbutton(
   -text     => '/ (optional delete line)',
   -variable => \$optional_delete,
  )->grid(
   -row    => 1,
   -column => 0,
  );

# Widget Text1 isa Text
$ZWIDGETS{'Text1'} = $MW->Text(
   -height => 30,
   -width  => 200,
  )->grid(
   -row        => 2,
   -column     => 0,
   -rowspan    => 2,
   -columnspan => 12,
  );

# Widget Button2 isa Button
$ZWIDGETS{'Button2'} = $MW->Button(
   -command => 'main::Output',
   -text    => 'Write File',
  )->grid(
   -row        => 4,
   -column     => 0,
   -rowspan    => 2,
   -columnspan => 3,
  );

# Widget Button4 isa Button
$ZWIDGETS{'Button4'} = $MW->Button(
   -command => 'main::load_options',
   -text    => 'Load Options',
  )->grid(
   -row    => 0,
   -column => 1,
  );

# Widget Label2 isa Label
$ZWIDGETS{'Label2'} = $MW->Label(
   -textvariable => \$NLine,
  )->grid(
   -row    => 1,
   -column => 1,
  );

# Widget Optionmenu1 isa Optionmenu
$ZWIDGETS{'Optionmenu1'} = $MW->Optionmenu(
   -command  => 'main::Set_UI',
   -variable => \$command,
  )->grid(
   -row    => 1,
   -column => 2,
  );

# Widget Label5 isa Label
$ZWIDGETS{'Label5'} = $MW->Label(
   -textvariable => \$param_1,
  )->grid(
   -row    => 1,
   -column => 3,
  );

# Widget Button3 isa Button
$ZWIDGETS{'Button3'} = $MW->Button(
   -command => 'main::pop',
   -text    => 'Pop from Queue',
  )->grid(
   -row        => 4,
   -column     => 3,
   -rowspan    => 2,
   -columnspan => 3,
  );

# Widget Entry4 isa Entry
$ZWIDGETS{'Entry4'} = $MW->Entry(
   -state        => 'normal',
   -textvariable => \$opt_1,
  )->grid(
   -row    => 1,
   -column => 4,
  );

# Widget Label6 isa Label
$ZWIDGETS{'Label6'} = $MW->Label(
   -textvariable => \$param_2,
  )->grid(
   -row    => 1,
   -column => 5,
  );

# Widget Entry5 isa Entry
$ZWIDGETS{'Entry5'} = $MW->Entry(
   -textvariable => \$opt_2,
  )->grid(
   -row    => 1,
   -column => 6,
  );

# Widget Label4 isa Label
$ZWIDGETS{'Label4'} = $MW->Label(
   -text => 'File Name:',
  )->grid(
   -row        => 4,
   -column     => 6,
   -columnspan => 3,
  );

# Widget Label3 isa Label
$ZWIDGETS{'Label3'} = $MW->Label(
   -text => 'File Extension:',
  )->grid(
   -row        => 5,
   -column     => 6,
   -columnspan => 3,
  );

# Widget Label7 isa Label
$ZWIDGETS{'Label7'} = $MW->Label(
   -textvariable => \$param_3,
  )->grid(
   -row    => 1,
   -column => 7,
  );

# Widget Entry6 isa Entry
$ZWIDGETS{'Entry6'} = $MW->Entry(
   -textvariable => \$opt_3,
  )->grid(
   -row    => 1,
   -column => 8,
  );

# Widget Label8 isa Label
$ZWIDGETS{'Label8'} = $MW->Label(
   -textvariable => \$param_4,
  )->grid(
   -row    => 1,
   -column => 9,
  );

# Widget Entry3 isa Entry
$ZWIDGETS{'Entry3'} = $MW->Entry(
   -textvariable => \$file,
  )->grid(
   -row        => 4,
   -column     => 9,
   -columnspan => 3,
  );

# Widget Entry2 isa Entry
$ZWIDGETS{'Entry2'} = $MW->Entry(
   -textvariable => \$ext,
  )->grid(
   -row        => 5,
   -column     => 9,
   -columnspan => 3,
  );

# Widget Entry7 isa Entry
$ZWIDGETS{'Entry7'} = $MW->Entry(
   -textvariable => \$opt_4,
  )->grid(
   -row    => 1,
   -column => 10,
  );

# Widget Button1 isa Button
$ZWIDGETS{'Button1'} = $MW->Button(
   -command => 'main::add_queue',
   -text    => 'Add to Queue',
  )->grid(
   -row    => 1,
   -column => 11,
  );

###############
#
# MainLoop
#
###############

MainLoop;

#######################
#
# Subroutines
#
#######################

sub ZloadImages {
}

sub ZloadFonts {
}

sub add_queue {

	$block = $command."\t".$opt_1."\t".$opt_2."\t".$opt_3."\t".$opt_4; 
	$block =~ s/\wnnn.nnn//g; 
	$block =~ s/or//g;
	$block =~ s/\*//g; 


	if ($optional_delete == 1) { 
		push(@queue, "/".$NLine."\t".$block."\n"); 
                $ZWIDGETS{'Text1'}->insert( '0.0', "/".$NLine."\t".$block."\n");
        } else { 
		push(@queue, $NLine."\t".$block."\n"); 
		$ZWIDGETS{'Text1'}->insert( '0.0', $NLine."\t".$block."\n");
        } 


	$line = $line + 1;
	$NLine = sprintf("N%04u", $line); 
}

sub load_options {
foreach my $k (keys %command_list) { 
        my $v = $command_list{$k};
	$ZWIDGETS{'Optionmenu1'}->addOptions([$k => $v]);
}
$ZWIDGETS{'Button4'} ->configure(-state=>'disabled'); 
}

sub Set_UI {
if ($command eq "G3") { 
	$param_1 = "X:";
	$param_2 = "Y:";
	$param_3 = "I or R:";
	$param_4 = "J or F:";
	$opt_1 = "Xnnn.nnn";
	$opt_2 = "Ynnn.nnn";
	$opt_3 = "Innn.nnn or Rnnn.nnn";
	$opt_4 = "Jnnn.nnn or Fnnn.nnn";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry6'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry7'}->configure(-state=>'normal');
}elsif ($command eq "G2") { 
	$param_1 = "X:";
	$param_2 = "Y:";
	$param_3 = "I or R:";
	$param_4 = "J or F:";
	$opt_1 = "Xnnn.nnn";
	$opt_2 = "Ynnn.nnn";
	$opt_3 = "Innn.nnn or Rnnn.nnn";
	$opt_4 = "Jnnn.nnn or Fnnn.nnn";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry6'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry7'}->configure(-state=>'normal');

}elsif ($command eq "M123") { 
	$param_1 = "IMax:";
	$param_2 = "*";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "Snnn.nnn";
	$opt_2 = "*";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');
}elsif ($command eq "M124") { 
	$param_1 = "IMin:";
	$param_2 = "*";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "Snnn.nnn";
	$opt_2 = "*";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');


}elsif ($command eq "G30") { 
	$param_1 = "X:";
	$param_2 = "Y:";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "Xnnn.nnn";
	$opt_2 = "Ynnn.nnn";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');


}elsif ($command eq "G0") { 
	$param_1 = "X";
	$param_2 = "Y";
	$param_3 = "Z";
	$param_4 = "*";
	$opt_1 = "Xnnn.nnn";
	$opt_2 = "Ynnn.nnn";
	$opt_3 = "Znnn.nnn";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry6'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');

}elsif ($command eq "M122") { 
	$param_1 = "D Gain:";
	$param_2 = "*";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "Snnn.nnn";
	$opt_2 = "*";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');
}elsif ($command eq "M123") { 
	$param_1 = "I Gain:";
	$param_2 = "*";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "Snnn.nnn";
	$opt_2 = "*";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');
}elsif ($command eq "M124") { 
	$param_1 = "P Gain:";
	$param_2 = "*";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "Snnn.nnn";
	$opt_2 = "*";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');
}elsif ($command eq "M109") { 
	$param_1 = "Temp:";
	$param_2 = "*";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "Snnn.nnn";
	$opt_2 = "*";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');
}elsif ($command eq "M104") { 
	$param_1 = "Temp:";
	$param_2 = "*";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "Snnn.nnn";
	$opt_2 = "*";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');
}elsif ($command eq "M113") { 
	$param_1 = "PWM:";
	$param_2 = "*";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "S0 to S1";
	$opt_2 = "*";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');
}elsif ($command eq "G1") { 
	$param_1 = "X or Y or Z:";
	$param_2 = "Speed:";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "Xnnn.nnn or Ynnn.nnn or Znnn.nnn";
	$opt_2 = "Fn.nn";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry5'}->configure(-state=>'normal');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');
} else { 
	$param_1 = "*";
	$param_2 = "*";
	$param_3 = "*";
	$param_4 = "*";
	$opt_1 = "*";
	$opt_2 = "*";
	$opt_3 = "*";
	$opt_4 = "*";
	$ZWIDGETS{'Entry4'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry5'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry6'}->configure(-state=>'disabled');
	$ZWIDGETS{'Entry7'}->configure(-state=>'disabled');
}
}

sub Output {

	open (F, ">>$file".$ext);

	foreach my $a (@queue) { 
		print F $a; 
	}

	close(F); 
}

sub pop {

	$ZWIDGETS{'Text1'}->delete('0.0','end');
	pop(@queue); 
        $line = $line - 1;
	$NLine = sprintf("N%04u", $line); 

	foreach my $a (@queue) { 
		$ZWIDGETS{'Text1'}->insert( '0.0', $a); 
	}
}

