#!perl

##################
#
# This file was automatically generated by ZooZ.pl v1.2
# on Tue Jul  1 09:58:26 2008.
# Project: Project 1
# File:    C:/Documents and Settings/matthew.dumas/Desktop/Tools Source Code/Renamer/rename.zooz
#
##################

#
# Headers
#
use strict;
use warnings;
use diagnostics;

use Tk 804;

#
# Global variables
#
my (
     # MainWindow
     $MW,

     # Hash of all widgets
     %ZWIDGETS,
    );

#
# User-defined variables (if any)
#
my $repl = ' ';

my $pat = ' ';

my $renamefiles = 'There are 0 files to rename.';

my $dir = 'C:\\';

my $info = undef;

my @files = ();

my $FT = '.bin';


######################
#
# Create the MainWindow
#
######################

$MW = MainWindow->new;

######################
#
# Load any images and fonts
#
######################
ZloadImages();
ZloadFonts ();



# Widget Button2 isa Button
$ZWIDGETS{'Button2'} = $MW->Button(
   -command => 'main::GetDir',
   -text    => 'Browse',
  )->grid(
   -row    => 1,
   -column => 0,
  );

# Widget Label6 isa Label
$ZWIDGETS{'Label6'} = $MW->Label(
   -text => 'Search String',
  )->grid(
   -row    => 2,
   -column => 0,
  );

# Widget Button1 isa Button
$ZWIDGETS{'Button1'} = $MW->Button(
   -command => 'main::Refresh',
   -text    => 'Refresh',
  )->grid(
   -row    => 3,
   -column => 0,
  );

# Widget Label8 isa Label
$ZWIDGETS{'Label8'} = $MW->Label(
   -text => 'System Messages',
  )->grid(
   -row    => 4,
   -column => 0,
  );

# Widget ROText1 isa ROText
$ZWIDGETS{'ROText1'} = $MW->ROText(
   -height => 24,
   -width  => 45,
  )->grid(
   -row        => 5,
   -column     => 0,
   -columnspan => 2,
  );

# Widget Label1 isa Label
$ZWIDGETS{'Label1'} = $MW->Label(
   -text => 'Location of Files to Rename:',
  )->grid(
   -row    => 0,
   -column => 1,
  );

# Widget Entry1 isa Entry
$ZWIDGETS{'Entry1'} = $MW->Entry(
   -textvariable => \$dir,
   -width        => 80,
  )->grid(
   -row        => 1,
   -column     => 1,
   -columnspan => 3,
  );

# Widget Entry2 isa Entry
$ZWIDGETS{'Entry2'} = $MW->Entry(
   -textvariable => \$info,
  )->grid(
   -row    => 2,
   -column => 1,
  );

# Widget Label10 isa Label
$ZWIDGETS{'Label10'} = $MW->Label(
   -text => 'File type: ',
  )->grid(
   -row    => 3,
   -column => 1,
  );

# Widget Label5 isa Label
$ZWIDGETS{'Label5'} = $MW->Label(
   -text         => 'Label5',
   -textvariable => \$renamefiles,
  )->grid(
   -row        => 4,
   -column     => 1,
   -columnspan => 2,
  );

# Widget Label7 isa Label
$ZWIDGETS{'Label7'} = $MW->Label(
   -text => 'Replace with:',
  )->grid(
   -row    => 2,
   -column => 2,
  );

# Widget Entry4 isa Entry
$ZWIDGETS{'Entry4'} = $MW->Entry(
   -textvariable => \$FT,
  )->grid(
   -row    => 3,
   -column => 2,
  );

# Widget ROText2 isa ROText
$ZWIDGETS{'ROText2'} = $MW->ROText(
   -height => 24,
   -width  => 45,
  )->grid(
   -row        => 5,
   -column     => 2,
   -columnspan => 2,
  );

# Widget Entry3 isa Entry
$ZWIDGETS{'Entry3'} = $MW->Entry(
   -textvariable => \$repl,
  )->grid(
   -row    => 2,
   -column => 3,
  );

# Widget Button3 isa Button
$ZWIDGETS{'Button3'} = $MW->Button(
   -command => 'main::RenameFiles',
   -text    => 'Rename Files',
  )->grid(
   -row    => 3,
   -column => 3,
  );

# Widget Label9 isa Label
$ZWIDGETS{'Label9'} = $MW->Label(
   -text => 'File List',
  )->grid(
   -row    => 4,
   -column => 3,
  );

###############
#
# MainLoop
#
###############

MainLoop;

#######################
#
# Subroutines
#
#######################

sub ZloadImages {
}

sub ZloadFonts {
}

sub RenameFiles {
my ($f,$new,$end,$fnum,@dump);

foreach $f (@files) { 
   $new = $f;
   $f =~ s/\///;
   $new =~ s/\///;
   $new =~ s/$info/$repl/;
   rename($f, $new);
}
 
}

sub GetDir {
$dir = $MW->chooseDirectory;
roprint('ROText1',"Changed location to: $dir\n");
chdir($dir); 
}

sub Refresh {
use Cwd;
use File::List;
use Data::Dumper;

my $search = new File::List($dir);
@files  = @{ $search->find($FT) };
@files =sort{ lc($a) cmp lc($b) } @files;

$renamefiles = "There are ".scalar(@files)." files to be renamed."; 
roprint('ROText1',"Refreshed file list.\n"); 
roprint('ROText2',"Files to be renamed:\n"); 

foreach my $s (@files) { 
   $s =~ s/$dir//;
   roprint('ROText2', $s."\n"); 
}

}

sub run {
   &Refresh; 
}

sub roprint {
my $box = $_[0]; 
my $dat = $_[1]; 
$ZWIDGETS{$box}->insert('end', $dat);
$ZWIDGETS{$box}->yview(moveto => 1);
}

